# =================================================================================================
# This code is part of PyLith, developed through the Computational Infrastructure
# for Geodynamics (https://github.com/geodynamics/pylith).
#
# This schema mirrors {packages/pylith/apps/gql}; keep the two in sync.
# =================================================================================================

# the server version
type Version {
    major: Int!
    minor: Int!
    micro: Int!
    revision: String!
}

# the top level query
type Query {
    version: Version!
}

# end of file
